# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uckb7EdAyP6Qw1ajIzIfZcLSQfTPKdnO
"""

# app.py
import streamlit as st
import pandas as pd

# Core 레포지토리 모듈 임포트 (경로 설정 필요)
# 실제 협업 시 git submodule 등을 통해 core 폴더를 가져왔다고 가정
from core.models import Subject
from core.algorithms import base_strategy, credit_priority_strategy, generate_timetables
from visualizer import draw_timetable

# Streamlit UI 설정
st.title("🎓 전략 패턴 기반 시간표 자동 생성기")

# 데이터 로드 (실제로는 Core의 data_loader 사용 권장)
df = pd.read_excel("core/subjects.xlsx")

# 사이드바/입력 UI
num_subjects = st.number_input("듣고 싶은 과목 개수", min_value=1, max_value=10, step=1)
# ... (나머지 UI 코드) ...

# 실행 버튼 로직
if st.button("시간표 생성하기"):
    # ... (데이터 필터링 및 Subject 객체 생성) ...

    subjects = [Subject(row["과목명"], row["요일"], row["시작시간"], row["종료시간"], row["학점"], row["강의실"])
                for _, row in filtered.iterrows()]

    # 전략 선택 및 실행
    strategy = base_strategy # 예시
    results = list(generate_timetables(subjects, num_subjects, strategy))

    # 결과 출력
    for idx, (tt, score) in enumerate(results):
        st.subheader(f"시간표 {idx+1} (점수: {score})")
        fig = draw_timetable(tt)
        st.pyplot(fig)