# -*- coding: utf-8 -*-
"""visualizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nHDkiGSOadpnsNS4-Cb9fDZ4fg-szdSg
"""

# visualizer.py
import matplotlib.pyplot as plt
import pandas as pd

# 한글 폰트 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

def draw_timetable(timetable):
    """Timetable 객체를 받아 matplotlib figure 반환"""
    days = ["월", "화", "수", "목", "금"]
    times = range(9, 18)  # 9시 ~ 17시

    df_table = pd.DataFrame(index=times, columns=days).fillna("")

    # 색상 매핑
    colors = ['#FF9999', '#66B2FF', '#99FF99', '#FFCC99', '#FFD700',
              '#DDA0DD', '#8FBC8F', '#F08080', '#AFEEEE', '#FFE4B5']
    color_map = {}

    for idx, subj in enumerate(timetable.subjects):
        color = colors[idx % len(colors)]
        color_map[subj.name] = color

        start, end = subj.time
        for t in range(start, end):
            if t in df_table.index:
                df_table.loc[t, subj.day] = f"{subj.name}\n({subj.room})"

    # 시각화 생성 로직 (Matplotlib)
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.axis("off")
    ax.axis("tight")

    # 테이블 생성 (색상 적용 로직 포함)
    cell_colours = []
    for r in range(len(df_table)):
        row_colors = []
        for c in range(len(df_table.columns)):
            val = df_table.iloc[r, c]
            color = "white"
            if val != "":
                subj_name = val.split("\n")[0]
                color = color_map.get(subj_name, "white")
            row_colors.append(color)
        cell_colours.append(row_colors)

    table = ax.table(cellText=df_table.values,
                     rowLabels=df_table.index,
                     colLabels=df_table.columns,
                     cellLoc='center',
                     loc='center',
                     cellColours=cell_colours)

    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1.2, 1.4)

    plt.title("전략 패턴 기반 자동 시간표", fontsize=13, pad=10)
    plt.tight_layout()
    return fig